### PR TITLE
simplify element hiding logic

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
Hi @zbarnz :slightly_smiling_face: 

I've found your [extension](https://chromewebstore.google.com/detail/hide-google-ai-overviews/neibhohkbmfjninidnaoacabkjonbahn) in the chrome extensions store, I really like the idea (and I would have made a similar extension (even just one unpublished for personal use) if yours didn't existed).

I've tested it and it doesn't really seem to work for me, I've had a quick look and figured that the hiding
logic could be simplified and made more robust (with no need for background tasks and storage permissions), so that's what this PR is doing :slightly_smiling_face: 

With my changes the extension does seem to be working nicely for me

Please have a look and let me know what you think :pray:

### CODE REVIEW

**Comment by zbarnz** [comment]
Hi @dario-piotrowicz thanks opening a PR. I will take a look when I get home from work. When i wasnt using background tasks I noticed there was a delay in hiding the overview and it would appear for a second. Curious to see if this resolved that.

**Comment by dario-piotrowicz** [comment]
> Hi @dario-piotrowicz thanks opening a PR. I will take a look when I get home from work.
> 
> When i wasnt using background tasks I noticed there was a delay in hiding the overview and it would appear for a second. Curious to see if this resolved that.

Thanks a bunch for the prompt response! :smiley: 

Sure, there's no rush :slightly_smiling_face: 

Actually I can see the overview for a fraction of a second too...

But I have an idea for removing that.... let me give it a quick try...

**Comment by dario-piotrowicz** [comment]
@zbarnz I've improved the solution so that we don't see the ai overview for even an instant! :smile: 

It makes the solution slightly more complicated but not terribly :slightly_smiling_face:

**Comment by zbarnz** [comment]
Works amazingly. Thank you very much

**Comment by dario-piotrowicz** [comment]
No problem, thanks a bunch for the prompt reviewing+merging :heart_hands:

**Pull request merged**
