### PR TITLE
add uk Top-Level-Domain

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
this PR adds the `.co.uk` TLD so that the extension can also work on `google.co.uk` :slightly_smiling_face: 

> [!Note]
> From the [google docs](https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns#special)
> it seems like they don't support TLD matching so I think all possible TLD sites need to be enumerated :confused:

### CODE REVIEW

**Review by zbarnz — APPROVED** [review]
Awesome, explains why its not working for some users. I will add the rest of googles supported domains

**Comment by dario-piotrowicz** [comment]
> Awesome, explains why its not working for some users. I will add the rest of googles supported domains

Yeah, I've added `.co.uk` since I am based in the UK I think it'd be ideal to all all english based google TLDs

You can also add all google possible TLDs but if you do that I'd imagine you should also update/internationalize the [matching logic](https://github.com/zbarnz/Google_AI_Overviews_Blocker/blob/dc870b8a34664bad26617e6b6c515d39a38a94e1/content.js#L3), it should be very straightforward implementation-wise, but I have no idea how to find all the possible combinations :sweat:  (language <-> ai overview heading text) also I have no idea to which regions google released this great feature (for example the UK just recently got it whilst it's been available in the US for some moths now as far as I understand)

if you'll have any idea on how to solve the above please let me know, in case you find something I'd be happy to help :smiley:

**Comment by zbarnz** [comment]
@dario-piotrowicz I added all of [Google's supported domains](https://www.google.com/supported_domains). I ran through a couple and it seems to be working for them. I also changed my language and it continued to work so the HTML tag doesn't change based on language.

**Comment by dario-piotrowicz** [comment]
@zbarnz yeah I did the same! :grin: 

I wouldn't be too surprised if it was only available in english regions for now...

anyways I think that adding all the supported domains it fine and won't hurt (at worst the extension just won't work there)

**Pull request merged**
